"""db/schema.py — SQLite şeması ve başlatma."""

_SCHEMA = """
CREATE TABLE IF NOT EXISTS shadow_candidates (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    ts                TEXT NOT NULL,
    slug              TEXT NOT NULL,
    asset             TEXT NOT NULL,
    action            TEXT NOT NULL,
    fair_value        REAL,
    best_ask          REAL,
    edge              REAL,
    passed            INTEGER NOT NULL,
    veto_layer        TEXT,
    veto_reason       TEXT,
    dry_run           INTEGER NOT NULL DEFAULT 1,
    confidence_score  REAL,
    kelly_f           REAL,
    seconds_remaining REAL
);

CREATE TABLE IF NOT EXISTS candidates (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    ts          TEXT NOT NULL,
    slug        TEXT NOT NULL,
    asset       TEXT NOT NULL,
    action      TEXT NOT NULL,
    fair_value  REAL,
    best_ask    REAL,
    edge        REAL,
    passed      INTEGER NOT NULL,
    veto_layer  TEXT,
    veto_reason TEXT,
    dry_run     INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS positions (
    position_id      TEXT PRIMARY KEY,
    ts_open          TEXT NOT NULL,
    slug             TEXT NOT NULL,
    asset            TEXT NOT NULL,
    action           TEXT NOT NULL,
    pm_entry_price   REAL,
    fair_value       REAL,
    ref_price        REAL,
    edge             REAL,
    position_usd     REAL,
    kelly_f          REAL,
    confidence_score REAL,
    status           TEXT NOT NULL DEFAULT 'open',
    ts_close         TEXT,
    pm_exit_price    REAL,
    exit_reason      TEXT,
    dry_run          INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS entry_air_pocket_events (
    id                                   INTEGER PRIMARY KEY AUTOINCREMENT,
    slug                                 TEXT,
    asset                                TEXT,
    action                               TEXT,
    market_id                            TEXT,
    token_id                             TEXT,
    event_ts                             TEXT,
    council_pass_ts                      TEXT,
    order_submit_ts                      TEXT,
    error_ts                             TEXT,
    council_to_submit_ms                 REAL,
    submit_to_error_ms                   REAL,
    fair                                 REAL,
    expected_ask                         REAL,
    original_worst_price                 REAL,
    original_fee_adj                     REAL,
    min_edge                             REAL,
    reported_liquidity                   REAL,
    top_of_book_size                     REAL,
    book_levels_used                     INTEGER,
    book_source                          TEXT,
    book_age_ms                          REAL,
    order_id                             TEXT,
    error_type                           TEXT,
    position_created                     INTEGER DEFAULT 0,
    fresh_ask_after_fail                 REAL,
    fresh_no_ask_after_fail              REAL,
    fresh_book_age_ms                    REAL,
    fresh_fee_adj_after_fail             REAL,
    fresh_price_delta_cents              REAL,
    fresh_edge_still_passes_min_edge     INTEGER,
    would_retry_passed_shadow            INTEGER,
    delayed_ask_after_fail               REAL,
    delayed_no_ask_after_fail            REAL,
    delayed_book_age_ms                  REAL,
    delayed_fee_adj_after_fail           REAL,
    delayed_price_delta_cents            REAL,
    delayed_edge_still_passes_min_edge   INTEGER,
    delayed_would_retry_passed_shadow    INTEGER
);

CREATE TABLE IF NOT EXISTS air_pocket_shadow (
    id                        INTEGER PRIMARY KEY AUTOINCREMENT,
    seq_no                    INTEGER,
    position_id               TEXT,
    slug                      TEXT,
    asset                     TEXT,
    action                    TEXT,
    current_exit_price        REAL,
    current_exit_result       TEXT,
    guarded_exit_decision     TEXT,
    decision_reason           TEXT,
    override_reason           TEXT,
    depth_ratio               REAL,
    pred_gap                  REAL,
    actual_trigger_fill_gap   REAL,
    post_wait_bid             REAL,
    post_wait_depth           REAL,
    post_wait_error           TEXT,
    would_have_improved_fill  INTEGER,
    false_positive_guard      INTEGER,
    shadow_compute_ms         REAL,
    live_exit_delay_ms        REAL,
    error                     TEXT,
    created_at                TEXT
);

CREATE TABLE IF NOT EXISTS shadow_positions (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    paper_id              TEXT UNIQUE,
    source_event_id       TEXT,
    ts_open               TEXT,
    slug                  TEXT,
    asset                 TEXT,
    action                TEXT,
    entry_price_estimated REAL,
    entry_method          TEXT,
    position_usd_paper    REAL,
    shares_paper          REAL,
    fair_value            REAL,
    edge                  REAL,
    ref_price             REAL,
    entry_hl_price        REAL,
    confidence_score      REAL,
    status                TEXT DEFAULT 'open',
    ts_close              TEXT,
    close_reason          TEXT,
    pm_exit_estimated     REAL,
    resolve_exit          REAL,
    mae_pct               REAL,
    mfe_pct               REAL,
    mfe_peak              REAL,
    cohort                TEXT DEFAULT 'paper',
    confidence_level      TEXT DEFAULT 'low',
    data_quality          TEXT,
    is_paper              INTEGER DEFAULT 1,
    dedupe_reason         TEXT,
    edge_bucket           TEXT,
    fee_adj_edge          REAL,
    depth_walk_estimated_fill        REAL,
    estimated_slippage_pct           REAL,
    net_ev_after_estimated_slippage  REAL,
    paper_viability       TEXT,
    yes_fair              REAL,
    no_fair               REAL,
    action_fair           REAL,
    entry_source          TEXT,
    snapshot_age_ms       REAL,
    seconds_remaining_at_signal  REAL,
    seconds_remaining_at_open    REAL,
    late_entry_flag       INTEGER,
    collapse_timing_flag  INTEGER,
    signal_timestamp_ms   INTEGER,
    created_at            TEXT
);

CREATE TABLE IF NOT EXISTS shadow_stop_events (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    paper_id             TEXT,
    ts                   TEXT,
    slug                 TEXT,
    asset                TEXT,
    action               TEXT,
    seconds_remaining    REAL,
    pm_price             REAL,
    drawdown_pct         REAL,
    hl_drift_pct         REAL,
    mae_pct              REAL,
    mfe_pct              REAL,
    mfe_peak             REAL,
    current_action       TEXT,
    conservative_action  TEXT,
    balanced_action      TEXT,
    mfe_breakeven_action TEXT,
    decision_reason      TEXT,
    paper_compute_ms     REAL,
    created_at           TEXT
);

CREATE TABLE IF NOT EXISTS shadow_model_pnl (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    paper_id          TEXT,
    model             TEXT,
    would_exit_price  REAL,
    would_exit_reason TEXT,
    would_exit_ts     TEXT,
    would_pnl         REAL,
    resolve_exit      REAL,
    cohort            TEXT DEFAULT 'paper',
    created_at        TEXT
);

CREATE TABLE IF NOT EXISTS tp_exit_measurements (
    id                     INTEGER PRIMARY KEY AUTOINCREMENT,
    paper_id               TEXT,
    slug                   TEXT,
    asset                  TEXT,
    action                 TEXT,
    tp_level               INTEGER,
    entry_price            REAL,
    shares                 REAL,
    real_tradable_tp_pnl   REAL,
    sell_avg_price         REAL,
    exit_slippage_pct      REAL,
    exit_levels_used       INTEGER,
    exit_book_age_ms       REAL,
    tp_hit_ts              TEXT,
    exit_depth_walk_source TEXT,
    created_at             TEXT,
    UNIQUE(paper_id, tp_level)
);

CREATE TABLE IF NOT EXISTS model_decision_events (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id                    TEXT UNIQUE,
    snapshot_id                 TEXT,
    timestamp                   TEXT,
    slug                        TEXT,
    asset                       TEXT,
    timeframe                   TEXT,
    action                      TEXT,
    model_version               TEXT,
    ref_price                   REAL,
    p_now                       REAL,
    best_bid                    REAL,
    best_ask                    REAL,
    spread                      REAL,
    snapshot_age_ms             REAL,
    raw_realized_vol            REAL,
    clamped_model_vol           REAL,
    vol_was_clamped             INTEGER,
    vol_clamp_min               REAL,
    vol_clamp_max               REAL,
    vol_source                  TEXT,
    vol_window                  TEXT,
    sigma_t                     REAL,
    z_score                     REAL,
    z_abs                       REAL,
    z_overconfidence_flag       INTEGER,
    z_overconfidence_threshold  REAL,
    vol_clamp_and_high_z        INTEGER,
    drift_term                  REAL,
    momentum_term               REAL,
    fair_yes                    REAL,
    fair_no                     REAL,
    action_fair                 REAL,
    fee_adjustment              REAL,
    net_ev                      REAL,
    fair_gap                    REAL,
    edge_bin                    TEXT,
    decision_threshold          REAL,
    would_enter                 INTEGER,
    skip_reason                 TEXT,
    created_at                  TEXT
);

CREATE TABLE IF NOT EXISTS tp_size_ladder (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    paper_id                    TEXT,
    slug                        TEXT,
    asset                       TEXT,
    action                      TEXT,
    timeframe                   TEXT,
    tp_level                    INTEGER,
    entry_price                 REAL,
    observed_return_pct         REAL,
    overshoot_pct               REAL,
    cadence_artifact_flag       INTEGER,
    simulated_exit_notional_usd REAL,
    shares_to_sell              REAL,
    avg_exit_price              REAL,
    exit_levels_used            INTEGER,
    exit_fill_complete          INTEGER,
    exit_unfilled_shares        REAL,
    real_tradable_tp_pnl        REAL,
    ideal_tp_pnl                REAL,
    conservative_tp_pnl         REAL,
    exit_slippage_pct           REAL,
    tradable_capacity_usd       REAL,
    tp_hit_ts                   TEXT,
    created_at                  TEXT,
    UNIQUE(paper_id, tp_level, simulated_exit_notional_usd)
);

CREATE TABLE IF NOT EXISTS paper_entry_events (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    paper_id         TEXT,
    ts               TEXT,
    slug             TEXT,
    asset            TEXT,
    action           TEXT,
    best_ask         REAL,
    depth_walk_price REAL,
    ask_buffer_price REAL,
    chosen_price     REAL,
    chosen_method    TEXT,
    book_levels      INTEGER,
    created_at       TEXT
);
"""


_MIGRATIONS = [
    "ALTER TABLE positions ADD COLUMN ref_price REAL",
    "ALTER TABLE positions ADD COLUMN edge REAL",
    "ALTER TABLE positions ADD COLUMN realized_pnl REAL",
    # CLOB API kolonları:
    "ALTER TABLE positions ADD COLUMN shares REAL",
    "ALTER TABLE positions ADD COLUMN order_id TEXT",
    "ALTER TABLE positions ADD COLUMN yes_token_id TEXT",
    "ALTER TABLE positions ADD COLUMN no_token_id TEXT",
    # Sira numarasi:
    "ALTER TABLE positions ADD COLUMN seq_no INTEGER",
    # HL fiyat kolonlari:
    "ALTER TABLE positions ADD COLUMN entry_hl_price REAL",
    "ALTER TABLE positions ADD COLUMN exit_hl_price REAL",
    # Faz 1: MAE/MFE + stop slippage + sell timing telemetrisi
    "ALTER TABLE positions ADD COLUMN mae_pct REAL",
    "ALTER TABLE positions ADD COLUMN mfe_pct REAL",
    "ALTER TABLE positions ADD COLUMN mae_px REAL",
    "ALTER TABLE positions ADD COLUMN mfe_px REAL",
    "ALTER TABLE positions ADD COLUMN mae_ts TEXT",
    "ALTER TABLE positions ADD COLUMN mfe_ts TEXT",
    "ALTER TABLE positions ADD COLUMN mae_data_quality TEXT",
    "ALTER TABLE positions ADD COLUMN price_source TEXT",
    "ALTER TABLE positions ADD COLUMN sl_trigger_px REAL",
    "ALTER TABLE positions ADD COLUMN sl_trigger_pct REAL",
    "ALTER TABLE positions ADD COLUMN first_trigger_ts TEXT",
    "ALTER TABLE positions ADD COLUMN exit_bid_at_trigger REAL",
    "ALTER TABLE positions ADD COLUMN exit_ask_at_trigger REAL",
    "ALTER TABLE positions ADD COLUMN spread_at_trigger REAL",
    "ALTER TABLE positions ADD COLUMN book_depth_at_trigger REAL",
    "ALTER TABLE positions ADD COLUMN sell_attempt_count INTEGER",
    "ALTER TABLE positions ADD COLUMN sell_unmatched_count INTEGER",
    "ALTER TABLE positions ADD COLUMN fill_ts TEXT",
    "ALTER TABLE positions ADD COLUMN sl_fill_px REAL",
    "ALTER TABLE positions ADD COLUMN sl_fill_pct REAL",
    "ALTER TABLE positions ADD COLUMN trigger_fill_gap_pct REAL",
    "ALTER TABLE positions ADD COLUMN trigger_to_fill_secs REAL",
    # Faz 2.2: Partial fill telemetri
    "ALTER TABLE positions ADD COLUMN partial_fill_count INTEGER DEFAULT 0",
    "ALTER TABLE positions ADD COLUMN partial_fill_shares REAL",
    "ALTER TABLE positions ADD COLUMN partial_realized_usdc REAL",
    # Faz 3: Entry execution telemetri
    "ALTER TABLE positions ADD COLUMN ask_at_decision REAL",
    "ALTER TABLE positions ADD COLUMN slippage_pct REAL",
    # Faz 3: Exit execution telemetri
    "ALTER TABLE positions ADD COLUMN sell_limit_price REAL",
    "ALTER TABLE positions ADD COLUMN first_exit_decision_ts TEXT",
    # Faz 4A-0: Shadow Mode entry depth telemetri (fire-and-forget, trade'i bloklamaz)
    "ALTER TABLE positions ADD COLUMN entry_top_book_size REAL",
    "ALTER TABLE positions ADD COLUMN entry_depth_for_size REAL",
    "ALTER TABLE positions ADD COLUMN entry_est_exit_price REAL",
    "ALTER TABLE positions ADD COLUMN entry_depth_slippage_pct REAL",
    "ALTER TABLE positions ADD COLUMN entry_book_levels_used INTEGER",
    # 4h shadow universe + fee telemetri
    "ALTER TABLE shadow_candidates ADD COLUMN timeframe TEXT",
    "ALTER TABLE shadow_candidates ADD COLUMN trade_enabled INTEGER DEFAULT 1",
    "ALTER TABLE shadow_candidates ADD COLUMN fee_adj_edge REAL",
    "ALTER TABLE shadow_candidates ADD COLUMN liquidity_usd REAL",
    "ALTER TABLE shadow_candidates ADD COLUMN spread REAL",
    # Edge bucket shadow experiment — paper cohort genişletmesi
    "ALTER TABLE shadow_positions ADD COLUMN edge_bucket TEXT",
    "ALTER TABLE shadow_positions ADD COLUMN fee_adj_edge REAL",
    "ALTER TABLE shadow_positions ADD COLUMN depth_walk_estimated_fill REAL",
    "ALTER TABLE shadow_positions ADD COLUMN estimated_slippage_pct REAL",
    "ALTER TABLE shadow_positions ADD COLUMN net_ev_after_estimated_slippage REAL",
    "ALTER TABLE shadow_positions ADD COLUMN paper_viability TEXT",
    # NO baseline + temporal snapshot handoff
    "ALTER TABLE shadow_positions ADD COLUMN yes_fair REAL",
    "ALTER TABLE shadow_positions ADD COLUMN no_fair REAL",
    "ALTER TABLE shadow_positions ADD COLUMN action_fair REAL",
    "ALTER TABLE shadow_positions ADD COLUMN entry_source TEXT",
    "ALTER TABLE shadow_positions ADD COLUMN snapshot_age_ms REAL",
    "ALTER TABLE shadow_positions ADD COLUMN seconds_remaining_at_signal REAL",
    "ALTER TABLE shadow_positions ADD COLUMN seconds_remaining_at_open REAL",
    "ALTER TABLE shadow_positions ADD COLUMN late_entry_flag INTEGER",
    "ALTER TABLE shadow_positions ADD COLUMN collapse_timing_flag INTEGER",
    "ALTER TABLE shadow_positions ADD COLUMN signal_timestamp_ms INTEGER",
    # TP size-ladder: eski küçük-size ölçümleri karantina
    "ALTER TABLE tp_exit_measurements ADD COLUMN measurement_cohort TEXT DEFAULT 'legacy_small_size'",
    # Telemetry V2: NO bid/ask + TTE + counterfactual + outcome link
    "ALTER TABLE model_decision_events ADD COLUMN telemetry_schema_version INTEGER DEFAULT 1",
    "ALTER TABLE model_decision_events ADD COLUMN yes_bid REAL",
    "ALTER TABLE model_decision_events ADD COLUMN yes_ask REAL",
    "ALTER TABLE model_decision_events ADD COLUMN no_bid REAL",
    "ALTER TABLE model_decision_events ADD COLUMN no_ask REAL",
    "ALTER TABLE model_decision_events ADD COLUMN bid_ask_source TEXT",
    "ALTER TABLE model_decision_events ADD COLUMN action_bid REAL",
    "ALTER TABLE model_decision_events ADD COLUMN action_ask REAL",
    "ALTER TABLE model_decision_events ADD COLUMN action_spread REAL",
    "ALTER TABLE model_decision_events ADD COLUMN time_to_expiry_seconds REAL",
    "ALTER TABLE model_decision_events ADD COLUMN time_to_expiry_ms REAL",
    "ALTER TABLE model_decision_events ADD COLUMN pricing_tte_years REAL",
    "ALTER TABLE model_decision_events ADD COLUMN pricing_model_tte_input REAL",
    "ALTER TABLE model_decision_events ADD COLUMN window_open_ts TEXT",
    "ALTER TABLE model_decision_events ADD COLUMN window_close_ts TEXT",
    "ALTER TABLE model_decision_events ADD COLUMN counterfactual_supported INTEGER",
    "ALTER TABLE model_decision_events ADD COLUMN counterfactual_missing_reason TEXT",
    "ALTER TABLE model_decision_events ADD COLUMN outcome_link_supported INTEGER",
    "ALTER TABLE model_decision_events ADD COLUMN tracking_key TEXT",
    "ALTER TABLE model_decision_events ADD COLUMN paper_id TEXT",
    "ALTER TABLE model_decision_events ADD COLUMN shadow_candidate_id TEXT",
    # Live Execution Faz 2a — order_intents (local idempotency + state machine)
    """CREATE TABLE IF NOT EXISTS order_intents (
        order_intent_id      TEXT PRIMARY KEY,
        slug                 TEXT,
        market_token_id      TEXT,
        side                 TEXT,
        intended_price       REAL,
        intended_size        REAL,
        payload_hash         TEXT,
        status               TEXT NOT NULL,
        intent_timestamp     TEXT,
        submitted_at         TEXT,
        wallet_address       TEXT,
        exchange_order_id    TEXT,
        matched_trade_id     TEXT,
        size_matched         REAL,
        reconciliation_status TEXT,
        reconciliation_reason TEXT,
        created_at           TEXT,
        updated_at           TEXT
    )""",
    # Outcome link: paper'lara tracking_key (V2 telemetri ↔ shadow_positions join)
    "ALTER TABLE shadow_positions ADD COLUMN tracking_key TEXT",
    # tracking_key EVENT-LEVEL UNIQUE (eski 4-parça duplicate'ler önce bad_v1: ile karantina edilir)
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_mde_tracking_key ON model_decision_events(tracking_key)",
    # Telemetry V3.1 — Data Integrity (Fix2 spread / Fix3 hl_drift)
    "ALTER TABLE model_decision_events ADD COLUMN spread_crossed_flag INTEGER",
    "ALTER TABLE model_decision_events ADD COLUMN bid_ask_consistent_spread REAL",
    "ALTER TABLE model_decision_events ADD COLUMN hl_drift_at_entry REAL",
    # Live Execution Faz 2c-2 — execution_state (kill-switch persist + runtime block)
    # Singleton satır (state_key='global'). emergency_paused=1 → execute() network call YOK.
    # Otomatik temizlik YASAK; yalnız clear_emergency_pause() (insan onayı). Fail-closed okuma.
    """CREATE TABLE IF NOT EXISTS execution_state (
        state_key        TEXT PRIMARY KEY,
        emergency_paused INTEGER NOT NULL DEFAULT 0,
        reason           TEXT,
        source           TEXT,
        order_intent_id  TEXT,
        created_at       TEXT,
        updated_at       TEXT
    )""",
    # Telemetry V3.1 — Lifecycle (Fix4 + 4.1 restart recovery)
    "ALTER TABLE shadow_positions ADD COLUMN time_to_mfe_s REAL",
    "ALTER TABLE shadow_positions ADD COLUMN time_to_mae_s REAL",
    "ALTER TABLE shadow_positions ADD COLUMN resolve_ts TEXT",
    "ALTER TABLE shadow_positions ADD COLUMN mfe_mae_time_valid INTEGER",
    "ALTER TABLE shadow_positions ADD COLUMN mfe_mae_time_invalid_reason TEXT",
    # Live Execution Faz 2c-3 — lineage: position ↔ order_intent bağlantısı
    # 2c-4 reconcile join'i için (positions.order_intent_id ↔ order_intents.order_intent_id).
    "ALTER TABLE positions ADD COLUMN order_intent_id TEXT",
    # Faz 2c Task H1 — duplicate accounting guard: aynı order_intent_id için ikinci position
    # YASAK (DB-level). Partial UNIQUE: eski/dry NULL lineage satırlarını DIŞLAR (çakışma yok).
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_positions_order_intent_id "
    "ON positions(order_intent_id) WHERE order_intent_id IS NOT NULL",
    # Faz 2c-4 Slice D — emergency_pause resolve protokolü: append-only audit log.
    # Singleton execution_state yalnız güncel flag tutar; her TRIP/RESOLVE olayı buraya
    # immutable satır olarak eklenir (trip alanları asla ezilmez; çoklu döngü korunur).
    """CREATE TABLE IF NOT EXISTS execution_state_events (
        event_id              INTEGER PRIMARY KEY AUTOINCREMENT,
        event_type            TEXT NOT NULL,
        ts                    TEXT NOT NULL,
        old_state             INTEGER,
        new_state             INTEGER NOT NULL,
        reason                TEXT,
        source                TEXT,
        order_intent_id       TEXT,
        observed_intent_state TEXT,
        resolved_by           TEXT,
        force                 INTEGER NOT NULL DEFAULT 0,
        verified              INTEGER NOT NULL DEFAULT 0
    )""",
    # ARAF B1 — A3-pure resolution shadow ledger (paper-first). decide_araf_resolution'ın
    # ResolutionResult'ı yalnız BURAYA yazılır; order_intents/positions DOKUNULMAZ (canlı state
    # machine / pozisyon yok). Idempotency anahtarı = order_intent_id (intent başına tek resolution).
    # Decimal alanlar TEXT (float yok). matched_trade_ids kanonik metin (data-order). Raw payload YOK.
    """CREATE TABLE IF NOT EXISTS araf_resolution_shadow (
        order_intent_id    TEXT PRIMARY KEY,
        exchange_order_id  TEXT,
        resolution_state   TEXT NOT NULL,
        matched_size       TEXT,
        avg_price          TEXT,
        fee_rate_bps       TEXT,
        matched_trade_ids  TEXT,
        accounting_source  TEXT,
        resolver_contract  TEXT NOT NULL DEFAULT 'v0',
        adapter_contract   TEXT NOT NULL DEFAULT 'v0',
        schema_version     INTEGER NOT NULL DEFAULT 1,
        recovery_reason    TEXT,
        created_at         TEXT NOT NULL
    )""",
    # Tier-0 PUBLIC_REFERENCE_BASKET evidence (radar, NOT trading). Append-only, isolated.
    # Numeric discipline: economic quantities are Decimal TEXT (REAL YASAK). Timing = INTEGER ms / TEXT.
    # SETTLEMENT_AUTHORITY=Chainlink (proven, auth-gated) is NOT required to collect; public basket
    # (Coinbase+Kraken USD spot) is the live proxy; Hyperliquid perp is a SEPARATE basis input.
    """CREATE TABLE IF NOT EXISTS reference_price_ticks (
        id                          INTEGER PRIMARY KEY AUTOINCREMENT,
        tick_id                     TEXT UNIQUE,
        source_name                 TEXT,
        source_type                 TEXT,
        asset                       TEXT,
        pair                        TEXT,
        quote                       TEXT,
        source_event_ts_raw         TEXT,
        source_event_ts_parse_status TEXT,
        collector_received_at       TEXT,
        ingest_skew_ms              INTEGER,
        fetch_started_at            TEXT,
        fetch_completed_at          TEXT,
        source_age_ms               INTEGER,
        price_raw                   TEXT,
        price_decimal_text          TEXT,
        raw_payload_json            TEXT,
        reject_reason               TEXT,
        schema_version              INTEGER,
        created_at                  TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS proxy_reference_basket_ticks (
        id                          INTEGER PRIMARY KEY AUTOINCREMENT,
        basket_id                   TEXT UNIQUE,
        asset                       TEXT,
        anchor_ts                   TEXT,
        coinbase_tick_id            TEXT,
        kraken_tick_id              TEXT,
        coinbase_fetch_started_at   TEXT,
        coinbase_fetch_completed_at TEXT,
        kraken_fetch_started_at     TEXT,
        kraken_fetch_completed_at   TEXT,
        basket_capture_span_ms      INTEGER,
        completion_skew_ms          INTEGER,
        coinbase_source_age_ms      INTEGER,
        kraken_source_age_ms        INTEGER,
        spot_reference_decimal_text TEXT,
        spread_bps_decimal_text     TEXT,
        spread_guard_status         TEXT,
        used_spot_sources_json      TEXT,
        excluded_sources_json       TEXT,
        max_source_age_ms           INTEGER,
        proxy_confidence            TEXT,
        not_official_chainlink      INTEGER DEFAULT 1,
        schema_version              INTEGER,
        created_at                  TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS perp_basis_ticks (
        id                              INTEGER PRIMARY KEY AUTOINCREMENT,
        basis_id                        TEXT UNIQUE,
        asset                           TEXT,
        proxy_basket_id                 TEXT,
        hyperliquid_tick_id             TEXT,
        hyperliquid_fetch_started_at    TEXT,
        hyperliquid_fetch_completed_at  TEXT,
        hyperliquid_source_age_ms       INTEGER,
        perp_price_decimal_text         TEXT,
        spot_reference_decimal_text     TEXT,
        basis_bps_decimal_text          TEXT,
        basis_direction                 TEXT,
        basis_quality_status            TEXT,
        schema_version                  INTEGER,
        created_at                      TEXT
    )""",
]


async def init_schema(conn) -> None:
    await conn.executescript(_SCHEMA)
    for sql in _MIGRATIONS:
        try:
            await conn.execute(sql)
        except Exception:
            pass  # sütun zaten varsa hata verir, yok say
    await conn.commit()
